apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv
  namespace: jenkins-leenhan
spec:
  storageClassName: jenkins-local-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
