apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: jenkins-leenhan
  labels:
    app: jenkins-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
  type: LoadBalancer
