apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: jenkins-local-pv
  local:
    path: /efs_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: hostname
          operator: In
          values:
            - worker1

